#define FREG_PNG                        101
#define COPPER_PNG                      102
#define GOLD_PNG                        103
#define SILVER_PNG                      104
#define REFRESH_PNG                     105
#define COG_PNG                         106
#define SAVE_PNG                        107
#define SEARCH_PNG                      108
#define BACKSPACE_PNG                   109
